### ISSUE TITLE
editable sections with links

### ISSUE THREAD

**Issue by levibrown** [javan/copy#2]
hi there
I have been checking out copy today and really like the editing interface you designed.
I did however run into a problem with editable sections with links. For example if I had a editable title that was also a link, when I use the bookmarklet to make it selectable and click it, it follows the link rather than open the markdown window.
I was thinking that there should be something in the index.js.erb to disable links while editing a page.

**Comment by javan** [comment]
Good suggestion. I'll work something up!

**Comment by javan** [comment]
All set: https://github.com/javan/copy/commit/a2c24e88ebb8608caeb1eb1cc080370fa18e7ed3

Version 0.1.5 released too. Thanks!

**Comment by levibrown** [comment]
Works great now, thanks!
