### ISSUE TITLE
unable to wrap content in p tags after content is empty 

### ISSUE THREAD

**Issue by levibrown** [javan/copy#4]
If you had a content block with a paragraph and then you delete it in markdown, then try to add multiple lines they will not be added as a paragraph because the paragraph tags are stripped out.

**Comment by javan** [comment]
Do you mean if you delete all the content and then save it and then try to add multiple lines again?

**Comment by levibrown** [comment]
yes

**Comment by javan** [comment]
Sounds like a link to turn the single line text field into a textarea would do the trick, no?

**Comment by levibrown** [comment]
yea, that sounds like a good approach to me. So, when the admin box opens there would be a link to toggle between the two?

**Comment by javan** [comment]
exactly, i'll make that happen.

**Comment by javan** [comment]
Version 0.1.6 is out with an automatically resizing textarea that should fix this for you. Just hit enter and the textarea will grow from a single line.
