### ISSUE TITLE
file uploader?

### ISSUE THREAD

**Issue by levibrown** [javan/copy#5]
I was wondering if you had plans to add a file uploader?
I was thinking it would be cool to have a basic uploader that would be protected at a location like /upload .
then there could possibly be a slide down menu where you could see the file names for reference in the markdown. I’m a amateur coder, but thought I could take a stab at if you didn’t have plans to do it.

And out of curiosity, what direction do you see copy going?

**Comment by javan** [comment]
This is a pretty big can of words that I don't see opening any time soon. Copy is all about text, and I specifically made it for using with heroku (although it works fine anywhere) which has a read-only filesystem so it would require uploading straight to S3 or some other service.
